import { NextRequest, NextResponse } from 'next/server';
import { VultrLLMService } from '@/lib/services/vultr-llm.service';

// Note: We always use CrewAI by default for consistent workflows

// Post-process SQL to ensure Trino/Iceberg compatibility
function cleanTrinoSQL(sql: string, databases: string[], catalog: string = 'iceberg'): string {
  const defaultCatalog = catalog;
  const defaultSchema = databases?.[0] || 'production';
  
  // Remove any USE statements (Trino doesn't support them)
  sql = sql.replace(/use\s+[^;]+;/gi, '');
  
  // Replace {db} placeholders with actual catalog.schema
  sql = sql.replace(/\{db\}/gi, `${defaultCatalog}.${defaultSchema}`);
  
  // Ensure table references without catalog are properly qualified
  // Match patterns like FROM tablename or JOIN tablename
  sql = sql.replace(/\b(FROM|JOIN|INTO)\s+([a-zA-Z_][a-zA-Z0-9_]*)\b/gi, (match, keyword, table) => {
    // Skip if already qualified (contains a dot)
    if (match.includes('.')) return match;
    // Skip common keywords that might be mistaken for tables
    if (['LATERAL', 'UNNEST', 'VALUES'].includes(table.toUpperCase())) return match;
    return `${keyword} ${defaultCatalog}.${defaultSchema}.${table}`;
  });
  
  // Fix any remaining schema.table patterns to catalog.schema.table
  sql = sql.replace(/\b([a-zA-Z_][a-zA-Z0-9_]*)\.([a-zA-Z_][a-zA-Z0-9_]*)\b/g, (match, schema, table) => {
    // Skip if already has catalog (contains two dots)
    if (sql.substring(sql.indexOf(match) - 20, sql.indexOf(match)).includes('.')) return match;
    // Skip function calls
    if (sql[sql.indexOf(match) + match.length] === '(') return match;
    // Check if this is likely a schema.table reference
    const beforeMatch = sql.substring(Math.max(0, sql.indexOf(match) - 10), sql.indexOf(match));
    if (beforeMatch.match(/(FROM|JOIN|INTO)\s*$/i)) {
      return `${defaultCatalog}.${schema}.${table}`;
    }
    return match;
  });
  
  return sql.trim();
}

// Call CrewAI for all SQL generation (default workflow)
async function callCrewAI(prompt: string, databases: string[], catalog: string): Promise<string> {
  try {
    const response = await fetch('http://localhost:3000/api/sql-crew', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        prompt,
        databases,
        catalog,
        mode: 'optimize',
        dialect: 'trino' // Explicitly set Trino dialect
      })
    });

    if (!response.ok) {
      throw new Error('CrewAI unavailable');
    }

    const result = await response.json();
    
    // Add metadata as comments
    const metadata = result.metadata;
    const analysis = result.analysis;
    
    let enhancedSQL = `-- Generated by CrewAI for Trino/Iceberg (Confidence: ${Math.round(metadata.confidence * 100)}%)\n`;
    
    if (analysis?.recommendations?.length > 0) {
      enhancedSQL += `-- Recommendations:\n`;
      analysis.recommendations.forEach((rec: string) => {
        enhancedSQL += `--   • ${rec}\n`;
      });
    }
    
    if (analysis?.cost !== undefined) {
      enhancedSQL += `-- Estimated cost: $${analysis.cost.toFixed(2)}\n`;
    }
    
    enhancedSQL += `\n${result.sql}`;
    
    // Clean up SQL for Trino/Iceberg
    return cleanTrinoSQL(enhancedSQL, databases, catalog);
  } catch (error) {
    console.log('CrewAI unavailable, falling back to standard generation');
    throw error;
  }
}

// Fallback SQL generator for Trino/Iceberg when APIs are unavailable
function generateFallbackSQL(prompt: string, refContent: string | null, databases: string[] | null, catalog: string = 'iceberg'): string {
  const lowerPrompt = prompt.toLowerCase();
  const schema = databases?.[0] || 'production';
  
  // Natural language patterns
  if (lowerPrompt.includes('show me') || lowerPrompt.includes('what are') || lowerPrompt.includes('find') || 
      lowerPrompt.includes('get') || lowerPrompt.includes('list')) {
    
    // Customer-related natural language queries
    if (lowerPrompt.includes('customer')) {
      if (lowerPrompt.includes('top') || lowerPrompt.includes('best')) {
        const limit = lowerPrompt.match(/(\d+)/)?.[1] || '10';
        
        if (lowerPrompt.includes('revenue') || lowerPrompt.includes('spending') || lowerPrompt.includes('value')) {
          return `-- Top customers by revenue
-- Natural language query: "${prompt}"
SELECT 
  c.customer_id,
  c.customer_name,
  c.email,
  c.segment,
  COUNT(DISTINCT o.order_id) as total_orders,
  SUM(o.order_amount) as total_revenue,
  AVG(o.order_amount) as avg_order_value,
  MAX(o.order_date) as last_order_date
FROM ${catalog}.${schema}.customers c
JOIN ${catalog}.${schema}.orders o ON c.customer_id = o.customer_id
WHERE o.status = 'completed'
GROUP BY c.customer_id, c.customer_name, c.email, c.segment
ORDER BY total_revenue DESC
LIMIT ${limit};`;
        }
        
        if (lowerPrompt.includes('recent') || lowerPrompt.includes('new')) {
          return `-- Recently acquired customers
-- Natural language query: "${prompt}"
SELECT 
  customer_id,
  customer_name,
  email,
  created_at,
  CURRENT_DATE - DATE(created_at) as days_since_signup
FROM ${catalog}.${schema}.customers
WHERE created_at >= CURRENT_DATE - INTERVAL '30' DAY
ORDER BY created_at DESC
LIMIT ${limit};`;
        }
      }
      
      if (lowerPrompt.includes('churn') || lowerPrompt.includes('inactive')) {
        return `-- Churned/Inactive customers
-- Natural language query: "${prompt}"
WITH last_orders AS (
  SELECT 
    customer_id,
    MAX(order_date) as last_order_date,
    COUNT(order_id) as total_orders
  FROM ${catalog}.${schema}.orders
  GROUP BY customer_id
)
SELECT 
  c.customer_id,
  c.customer_name,
  c.email,
  lo.last_order_date,
  lo.total_orders,
  CURRENT_DATE - DATE(lo.last_order_date) as days_since_last_order
FROM ${catalog}.${schema}.customers c
JOIN last_orders lo ON c.customer_id = lo.customer_id
WHERE lo.last_order_date < CURRENT_DATE - INTERVAL '90' DAY
ORDER BY days_since_last_order DESC;`;
      }
    }
    
    // Product-related natural language queries
    if (lowerPrompt.includes('product') || lowerPrompt.includes('item')) {
      if (lowerPrompt.includes('best selling') || lowerPrompt.includes('popular') || lowerPrompt.includes('top')) {
        return `-- Best selling products
-- Natural language query: "${prompt}"
SELECT 
  p.product_id,
  p.product_name,
  p.category,
  COUNT(DISTINCT o.order_id) as orders_count,
  SUM(oi.quantity) as units_sold,
  SUM(oi.quantity * oi.unit_price) as total_revenue,
  AVG(oi.unit_price) as avg_selling_price
FROM ${catalog}.${schema}.products p
JOIN ${catalog}.${schema}.order_items oi ON p.product_id = oi.product_id
JOIN ${catalog}.${schema}.orders o ON oi.order_id = o.order_id
WHERE o.order_date >= CURRENT_DATE - INTERVAL '30' DAY
  AND o.status = 'completed'
GROUP BY p.product_id, p.product_name, p.category
ORDER BY total_revenue DESC
LIMIT 20;`;
      }
      
      if (lowerPrompt.includes('trend') || lowerPrompt.includes('growth')) {
        return `-- Product sales trends
-- Natural language query: "${prompt}"
SELECT 
  DATE_TRUNC('week', o.order_date) as week,
  p.category,
  COUNT(DISTINCT o.order_id) as orders,
  SUM(oi.quantity) as units_sold,
  SUM(oi.quantity * oi.unit_price) as revenue
FROM ${catalog}.${schema}.products p
JOIN ${catalog}.${schema}.order_items oi ON p.product_id = oi.product_id
JOIN ${catalog}.${schema}.orders o ON oi.order_id = o.order_id
WHERE o.order_date >= CURRENT_DATE - INTERVAL '90' DAY
GROUP BY DATE_TRUNC('week', o.order_date), p.category
ORDER BY week DESC, revenue DESC;`;
      }
    }
    
    // Sales/Revenue natural language queries
    if (lowerPrompt.includes('sales') || lowerPrompt.includes('revenue')) {
      if (lowerPrompt.includes('daily') || lowerPrompt.includes('day')) {
        return `-- Daily sales report
-- Natural language query: "${prompt}"
SELECT 
  DATE(order_date) as date,
  COUNT(DISTINCT customer_id) as unique_customers,
  COUNT(order_id) as total_orders,
  SUM(order_amount) as total_revenue,
  AVG(order_amount) as avg_order_value
FROM ${catalog}.${schema}.orders
WHERE order_date >= CURRENT_DATE - INTERVAL '30' DAY
  AND status = 'completed'
GROUP BY DATE(order_date)
ORDER BY date DESC;`;
      }
      
      if (lowerPrompt.includes('month') || lowerPrompt.includes('monthly')) {
        return `-- Monthly sales summary
-- Natural language query: "${prompt}"
SELECT 
  DATE_TRUNC('month', order_date) as month,
  COUNT(DISTINCT customer_id) as unique_customers,
  COUNT(order_id) as total_orders,
  SUM(order_amount) as total_revenue,
  AVG(order_amount) as avg_order_value
FROM ${catalog}.${schema}.orders
WHERE order_date >= CURRENT_DATE - INTERVAL '12' MONTH
  AND status = 'completed'
GROUP BY DATE_TRUNC('month', order_date)
ORDER BY month DESC;`;
      }
    }
  }
  
  // Pattern matching for common SQL queries
  if (lowerPrompt.includes('top') && lowerPrompt.includes('customer')) {
    const limit = lowerPrompt.match(/top (\d+)/)?.[1] || '10';
    
    if (lowerPrompt.includes('revenue') || lowerPrompt.includes('sales')) {
      return `-- Top customers by revenue (Trino/Iceberg)
SELECT 
  c.customer_id,
  c.customer_name,
  c.email,
  SUM(o.order_amount) as total_revenue,
  COUNT(o.order_id) as total_orders
FROM ${catalog}.${schema}.customers c
LEFT JOIN ${catalog}.${schema}.orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name, c.email
ORDER BY total_revenue DESC
LIMIT ${limit};`;
    }
  }
  
  // Default Trino/Iceberg SELECT
  return `-- Generated SQL for: ${prompt}
-- Could not understand the natural language query, providing a template
SELECT *
FROM ${catalog}.${schema}.customers -- Change table as needed
WHERE 1=1
  -- Add your conditions here
LIMIT 10;`;
}

export async function POST(request: NextRequest) {
  try {
    const { prompt, refContent, databases, catalog = 'iceberg', environment = 'production' } = await request.json();

    // Initialize Vultr LLM service
    const llmService = new VultrLLMService();

    // Detect if the prompt is natural language vs SQL
    const isNaturalLanguage = !prompt.trim().toLowerCase().match(/^(select|insert|update|delete|create|drop|alter|with)\s/);
    
    // Create Trino/Iceberg-specific system prompt
    const systemPrompt = `You are an expert Trino SQL query generator with natural language understanding for a data lakehouse platform.

CURRENT ENVIRONMENT: ${environment.toUpperCase()}
${environment === 'production' ? 'IMPORTANT: This is PRODUCTION. Be extra careful with queries that modify data.' : ''}

NATURAL LANGUAGE UNDERSTANDING:
${isNaturalLanguage ? `The user is asking a question in natural language. Translate their business request into SQL.

Common business terms mapping:
- "top customers" = customers ordered by revenue/orders
- "best selling" = products/items ordered by sales volume
- "recent" = within last 7-30 days
- "performance" = metrics like revenue, conversion, growth
- "trending" = time-series analysis with growth calculation
- "churn" = customers who stopped ordering
- "active" = recent activity within threshold period` : 'The user provided SQL directly. Optimize and ensure it follows Trino syntax.'}

IMPORTANT REQUIREMENTS:
1. Generate ONLY Trino-compatible SQL syntax
2. Use fully qualified table names: catalog.schema.table (e.g., ${catalog}.${databases?.[0] || 'production'}.customers)
3. Default catalog is '${catalog}', default schema is '${databases?.[0] || 'production'}'
4. NEVER use 'USE' statements - Trino doesn't support them
5. NEVER use placeholders like {db} or {schema} - use actual names
6. Use Trino date/time syntax: CURRENT_DATE, INTERVAL '30' DAY (not DATE_SUB)
7. For Iceberg tables, you can use time travel: SELECT * FROM table FOR TIMESTAMP AS OF timestamp
${environment !== 'production' ? '8. In non-production environments, you may use LIMIT clauses more liberally for testing' : '8. In production, be mindful of query performance and resource usage'}

AVAILABLE TABLES AND COLUMNS:
- ${catalog}.${databases?.[0] || 'production'}.customers (customer_id, customer_name, email, created_at, status, segment)
- ${catalog}.${databases?.[0] || 'production'}.orders (order_id, customer_id, order_date, order_amount, status, payment_method)
- ${catalog}.${databases?.[0] || 'production'}.order_items (item_id, order_id, product_id, quantity, unit_price, discount)
- ${catalog}.${databases?.[0] || 'production'}.products (product_id, product_name, category, price, cost, created_at)
- ${catalog}.${databases?.[0] || 'production'}.events (event_id, user_id, event_type, event_data, timestamp)

Available schemas in ${catalog} catalog: ${databases?.join(', ') || 'production, analytics'}

Example correct format:
SELECT * FROM ${catalog}.${databases?.[0] || 'production'}.customers WHERE created_at >= CURRENT_DATE - INTERVAL '7' DAY

Guidelines:
1. ${isNaturalLanguage ? 'Translate the natural language query into optimized SQL' : 'Generate clean, optimized Trino SQL'}
2. Use proper JOIN syntax optimized for Trino's distributed execution
3. Consider Iceberg's partitioning for performance (common partitions: day, month, year)
4. Add comments explaining the business logic for complex queries
5. Include appropriate aggregations and groupings for analytical queries

Reference SQL (if any): ${refContent || 'None'}`;

    const userPrompt = `Generate a SQL query for: ${prompt}`;

    let generatedSQL: string;
    
    // Always use CrewAI by default for consistent workflows
    try {
      console.log('Using CrewAI for SQL generation...');
      generatedSQL = await callCrewAI(prompt, databases || ['production'], catalog);
    } catch (crewError) {
      console.warn('CrewAI unavailable, trying Vultr LLM...');
      
      // Fall back to Vultr LLM
      try {
        generatedSQL = await llmService.analyze({
          systemPrompt,
          userPrompt,
          temperature: 0.3,
          maxTokens: 1000,
          responseFormat: 'text'
        });
        // Clean up the Vultr response for Trino/Iceberg
        generatedSQL = cleanTrinoSQL(generatedSQL, databases, catalog);
      } catch (llmError) {
        console.warn('Vultr LLM also unavailable, using fallback generator');
        generatedSQL = generateFallbackSQL(prompt, refContent, databases, catalog);
      }
    }

    // Format and clean the SQL response
    let formattedSQL = generatedSQL.trim().startsWith('--') 
      ? generatedSQL 
      : `-- Generated SQL for Trino/Iceberg: ${prompt}\n${generatedSQL}`;
    
    // Final cleanup pass
    formattedSQL = cleanTrinoSQL(formattedSQL, databases, catalog);

    return NextResponse.json({
      status: 'success',
      message: formattedSQL,
      extra: {
        model: 'mistral-nemo-instruct-2407',
        databases: databases || ['production', 'analytics'],
        catalog: catalog,
        environment: environment
      }
    });

  } catch (error) {
    console.error('TiSQL AI Error:', error);
    
    return NextResponse.json({
      status: 'error',
      message: `-- Error generating SQL\n-- ${error instanceof Error ? error.message : 'Unknown error occurred'}`,
      extra: { error: true }
    }, { status: 500 });
  }
}

// Optional: GET endpoint for testing
export async function GET() {
  return NextResponse.json({
    service: 'TiSQL AI Assistant',
    status: 'operational',
    model: 'mistral-nemo-instruct-2407',
    provider: 'Vultr'
  });
}